# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"xml_to_jsonl": "data-preprocessing.ipynb",
         "writeHeader": "markup-to-spacy.ipynb",
         "writeFooter": "markup-to-spacy.ipynb"}

modules = ["preprocessing.py",
           "markup2spacy.py"]

doc_url = "https://d-genk.github.io/ssda_nlp/"

git_url = "https://github.com/d-genk/ssda_nlp/tree/master/"

def custom_doc_links(name): return None
