# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parse_xml": "12-ssda-xml-parser.ipynb",
         "parse_xml_v2": "12-ssda-xml-parser.ipynb",
         "retrieve_volume_metadata": "12-ssda-xml-parser.ipynb",
         "genAltEnts": "31-collate-xml-entities-spans.ipynb",
         "generateSpans": "31-collate-xml-entities-spans.ipynb",
         "parseEntities": "31-collate-xml-entities-spans.ipynb",
         "parseManualEntities": "31-collate-xml-entities-spans.ipynb",
         "parseXML": "31-collate-xml-entities-spans.ipynb",
         "genEntryIDs": "31-collate-xml-entities-spans.ipynb",
         "collate_frames": "31-collate-xml-entities-spans.ipynb",
         "manual_collate": "31-collate-xml-entities-spans.ipynb",
         "genSpaCyInput": "31-collate-xml-entities-spans.ipynb",
         "frames_to_spacy": "31-collate-xml-entities-spans.ipynb",
         "split_data": "33-split-data.ipynb",
         "split_data_grp": "33-split-data.ipynb",
         "load_model": "41-generic-framework-for-spacy-training.ipynb",
         "train_model": "41-generic-framework-for-spacy-training.ipynb",
         "save_model": "41-generic-framework-for-spacy-training.ipynb",
         "test_model": "41-generic-framework-for-spacy-training.ipynb",
         "model_meta_training": "42-initial-model.ipynb",
         "get_ner_df": "42-initial-model.ipynb",
         "get_corrects_df": "42-initial-model.ipynb",
         "get_fns_df": "42-initial-model.ipynb",
         "get_fps_df": "42-initial-model.ipynb",
         "xml_to_jsonl": "51-data-preprocessing.ipynb",
         "parse_annotation": "51-data-preprocessing.ipynb",
         "prodigy_output_to_collated_df": "51-data-preprocessing.ipynb",
         "writeHeader": "53-markup-to-spatial-historian.ipynb",
         "writeFooter": "53-markup-to-spatial-historian.ipynb",
         "universal_markup_converter": "52-unstructured-to-markup.ipynb",
         "process_brazilian_transcriptions": "52-unstructured-to-markup.ipynb",
         "new_file": "54-utility-functions.ipynb",
         "retrieve_controlled_vocabularies": "71-relationship-builder.ipynb",
         "categorize_characteristics": "71-relationship-builder.ipynb",
         "assign_characteristics": "71-relationship-builder.ipynb",
         "assign_relationships": "71-relationship-builder.ipynb",
         "id_unique_individuals": "71-relationship-builder.ipynb",
         "find_sus": "71-relationship-builder.ipynb",
         "split_name_col": "71-relationship-builder.ipynb",
         "disambiguate": "71-relationship-builder.ipynb",
         "determine_principals": "71-relationship-builder.ipynb",
         "determine_event_date": "71-relationship-builder.ipynb",
         "determine_event_location": "71-relationship-builder.ipynb",
         "identify_cleric": "71-relationship-builder.ipynb",
         "build_event": "71-relationship-builder.ipynb",
         "drop_obvious_duplicates": "71-relationship-builder.ipynb",
         "assign_unique_ids": "71-relationship-builder.ipynb",
         "build_entry_metadata": "71-relationship-builder.ipynb"}

modules = ["xml_parser.py",
           "collate.py",
           "split_data.py",
           "modeling.py",
           "model_performance_utils.py",
           "preprocessing.py",
           "unstructured2markup.py",
           "markup2sh.py",
           "utility.py",
           "relationships.py"]

doc_url = "https://d-genk.github.io/ssda_nlp/"

git_url = "https://github.com/d-genk/ssda_nlp/tree/master/"

def custom_doc_links(name): return None
