# AUTOGENERATED! DO NOT EDIT! File to edit: SSDA markup to spaCy input.ipynb (unless otherwise specified).

__all__ = ['writeHeader', 'writeFooter']

# Cell

def writeHeader(title, out, id=None):
    out.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
    out.write("<!--" + title + "-->\n")
    out.write("<ssda xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n")
    out.write("<volume>\n")
    out.write("<volumeTitle>" + title + "</volumeTitle>\n")
    if id != None:
        out.write("<volumeIdentifier>" + id + "</volumeIdentifier>")
    else:
        out.write("<volumeIdentifier />\n")
    out.write("<volumeGuid />\n")

# Cell

def writeFooter(out):
    out.write("</volume>\n")
    out.write("</ssda>\n")