# AUTOGENERATED! DO NOT EDIT! File to edit: data-preprocessing.ipynb (unless otherwise specified).

__all__ = ['xml_to_jsonl']

# Cell

def xml_to_jsonl(path_to_xml_transcription):
    xml_transcription = open(path_to_xml_transcription, 'r', encoding="utf-8")
    prodigy_input = open(path_to_xml_transcription[:path_to_xml_transcription.find(".xml")] + ".jsonl", 'w', encoding="utf-8")

    in_entry = False
    current_entry = ''

    for line in xml_transcription:
        if "<entry>" in line:
            in_entry = True
        elif in_entry and ("</entry>" in line):
            current_entry += line[:line.find("</entry>")]
            in_entry = False
            prodigy_input.write("{\"text\":\"" + current_entry + "\"}\n")
            current_entry = ''
        elif in_entry:
            if ((line[len(line) - 1] == '\n') or (line[len(line) - 1] == '\r')) and (line[len(line) - 2] == '-'):
                current_entry += line[:len(line) - 2]
            elif line[len(line) - 1] == '-':
                current_entry += line[:len(line) - 1]
            elif (line[len(line) - 1] == '\n') or (line[len(line) - 1] == '\r'):
                current_entry += line[:len(line) - 1] + ' '
            else:
                current_entry += line

    xml_transcription.close()
    prodigy_input.close()

    return