# AUTOGENERATED! DO NOT EDIT! File to edit: 54-utility-functions.ipynb (unless otherwise specified).

__all__ = ['new_file', 'normalize_text', 'compare_dates', 'complete_date']

# Cell

import json

# Cell

def new_file(files_list):
    with open('new_file.xml', 'w', encoding = "utf-8") as outfile:
        for names in files_list:
            with open(names, encoding = "utf-8") as infile:
                outfile.write(infile.read())
            outfile.write("\n")

    return

# Cell

def normalize_text(text, path_to_dict, context=None):
    '''
    normalizes transcribed text by expanding abbreviations, correcting idiosyncratic spellings, etc.
        text: text to be normalized, as a string
        path_to_dict: path to a JSON file containing baseword-synonym key-value pairs
        context: specific normalization context, if applicable

        returns: normalized text, as a string
    '''
    with open(path_to_dict) as infile:
        synonyms = json.load(infile)

    for word in synonyms["words"]:
        if (context != None) and ("context" in word) and (context != word["context"]):
            print("skipping out of context word " + word["baseword"])
            continue
        for synonym in word["synonyms"]:
            text = (' ' + text + ' ').replace(' ' + synonym + ' ', ' ' + word["baseword"] + ' ')
            text = text[1:len(text) - 1]

    return text

# Cell

def compare_dates(year1, month1, day1, year2, month2, day2):
    if year1 > year2:
        return '>'
    elif year1 < year2:
        return '<'
    elif month1 > month2:
        return '>'
    elif month1 < month2:
        return '<'
    elif day1 > day2:
        return '>'
    elif day1 < day2:
        return '<'
    else:
        return '='

# Cell

def complete_date(date, pvs_date, subs_date):

    year = date[:4]
    month = date[5:7]
    day = date[8:]

    if pvs_date == None:
        subs_year = subs_date[:4]
        subs_month = subs_date[5:7]
        subs_day = subs_date[8:]
        if year == "????":
            return "/" + subs_date
        else:
            if month == "??":
                if day == "??":
                    if year == subs_year:
                        return year + '-01-01/' + subs_date
                    else:
                        return year + '-01-01/' + year + '-12-31'
                else:
                    if year == subs_year:
                        return year + '-01' + day + '/' + subs_date
                    else:
                        return year + '-01' + day + '/' + year + '-12-' + day
            else:
                next_month = str(int(month) + 1)
                if len(next_month) == 1:
                    next_month = '0' + next_month
                return year + '-' + month + '-01/' + year + '-' + next_month + '-01'
    elif subs_date == None:
        pvs_year = pvs_date[:4]
        pvs_month = pvs_date[5:7]
        pvs_day = pvs_date[8:]
        if year == "????":
            if month == "??":
                if day == "??":
                    return pvs_date + '/'
                elif day < pvs_day:
                    if pvs_month == "12":
                        year = str(int(pvs_year) + 1)
                        return year + '-01-' + day + '/'
                    else:
                        month = str(int(pvs_month) + 1)
                        if len(month) == 1:
                            month = '0' + month
                        return pvs_year + '-' + month + '-' + day + '/'
                else:
                    return pvs_year + '-' + pvs_month + '-' + day + '/'
            elif month < pvs_month:
                year = str(int(pvs_year) + 1)
                if day == "??":
                    return year + '-' + month + '-01/'
                else:
                    return year + '-' + month + '-' + day + '/'
            else:
                if day == "??":
                    return pvs_year + '-' + month + '-01/'
                else:
                    return pvs_year + '-' + month + '-' + day + '/'
        elif month != "??":
            next_month = str(int(month) + 1)
            if len(next_month) == 1:
                next_month = '0' + next_month
            return year + '-' + month + '-01/' + year + '-' + next_month + '-01'
        elif day != "??":
            if year == pvs_year:
                return year + '-' + pvs_month + '-' + day + '/' + year + '-12-' + day
            else:
                return year + '-01-' + day + '/' + year + '-12-' + day
        else:
            if year == pvs_year:
                return year + '-' + pvs_month + '-' + pvs_day + '/' + year + '-12-31'
            else:
                return year + '-01-01/' + year + '-12-31'
    else:
        subs_year = subs_date[:4]
        subs_month = subs_date[5:7]
        subs_day = subs_date[8:]
        pvs_year = pvs_date[:4]
        pvs_month = pvs_date[5:7]
        pvs_day = pvs_date[8:]

        if (subs_year == pvs_year) and (subs_month == pvs_month) and (subs_day == pvs_day):
            return pvs_year + '-' + pvs_month + '-' + pvs_day

        if year == "????":
            if month == "??":
                if day == "??":
                    return pvs_date + '/' + subs_date
                elif (int(day) >= int(pvs_day)) and (int(day) <= int(subs_day)):
                    return pvs_year + '-' + pvs_month + '-' + day + '/' + subs_year + '-' + subs_month + '-' + day
                elif (int(day) >= int(pvs_day)):
                    subs_month = str(int(subs_month) - 1)
                    if len(subs_month) == 1:
                        subs_month = '0' + subs_month
                    if subs_month == "00":
                        subs_month = "12"
                        subs_year = str(int(subs_year) - 1)
                    return pvs_year + '-' + pvs_month + '-' + day + '/' + subs_year + '-' + subs_month + '-' + day
                elif (int(day) <= int(subs_day)):
                    pvs_month = str(int(subs_month) + 1)
                    if len(pvs_month) == 1:
                        pvs_month = '0' + pvs_month
                    return pvs_year + '-' + pvs_month + '-' + day + '/' + subs_year + '-' + subs_month + '-' + day
                else:
                    subs_month = str(int(subs_month) - 1)
                    if len(subs_month) == 1:
                        subs_month = '0' + subs_month
                    if subs_month == "00":
                        subs_month = "12"
                    subs_year = str(int(subs_year) - 1)
                    pvs_month = str(int(subs_month) + 1)
                    if len(pvs_month) == 1:
                        pvs_month = '0' + pvs_month
                    return pvs_year + '-' + pvs_month + '-' + day + '/' + subs_year + '-' + subs_month + '-' + day
            else:
                if day == "??":
                    next_month = str(int(month) + 1)
                    if len(next_month) == 1:
                        next_month = '0' + next_month
                    if pvs_year == subs_year:
                        return pvs_year + '-' + month + '-01/' + subs_year + '-' + next_month + '-01'
                    elif (int(month) >= int(pvs_month)) and (int(month) <= int(subs_month)):
                        return pvs_year + '-' + month + '-01/' + subs_year + '-' + next_month + '-01'
                    elif (int(month) >= int(pvs_month)):
                        subs_year = int(subs_year) - 1
                        return pvs_year + '-' + month + '-01/' + subs_year + '-' + next_month + '-01'
                    elif (int(month) <= int(subs_month)):
                        pvs_year = int(pvs_year) + 1
                        return pvs_year + '-' + month + '-01/' + subs_year + '-' + next_month + '-01'
                else:
                    if pvs_year == subs_year:
                        return pvs_year + '-' + month + '-' + day
                    else:
                        return pvs_year + '-' + month + '-' + day + '/' + subs_year + '-' + month + '-' + day
        else:
            if month == "??":
                if day == "??":
                    if (pvs_year == year) and (subs_year == year):
                        return year + '-' + pvs_month + '-' + pvs_day + '/' + year + '-' + subs_month + '-' + subs_day
                    elif (pvs_year == year):
                        return year + '-' + pvs_month + '-' + pvs_day + '/' + year + '-12-31'
                    elif (subs_year == year):
                        return year + '-01-01/' + year + '-' + subs_month + '-' + subs_day
                    else:
                        return year + '-01-01/' + year + '-12-31'
                else:
                    if (pvs_year == year) and (subs_year == year) and (pvs_month == subs_month):
                        return year + '-' + pvs_month + '-' + day
                    elif(pvs_year == year) and (subs_year == year):
                        return year + '-' + pvs_month + '-' + day + '/' + year + '-' + subs_month + '-' + day
                    elif (pvs_year == year) and (pvs_day <= day):
                        return year + '-' + pvs_month + '-' + day + '/' + year + '-12-' + day
                    elif (pvs_year == year):
                        next_month = str(int(month) + 1)
                        if len(next_month) == 1:
                            next_month = '0' + next_month
                        return year + '-' + next_month + '-' + day + '/' + year + '-12-' + day
                    elif (subs_year == year) and (subs_day >= day):
                        return year + '-01-' + day + '/' + year + '-' + subs_month + '-' + day
                    elif (subs_year == year):
                        subs_month = str(int(subs_month) - 1)
                        if len(subs_month) == 1:
                            subs_month = '0' + subs_month
                        if subs_month == "00":
                            subs_month = "12"
                        return year + '-01-' + day + '/' + year + '-' + subs_month + '-' + day
                    else:
                        return year + '-01-' + day + '/' + year + '-12-' + day

            else:
                next_month = str(int(month) + 1)
                if len(next_month) == 1:
                    next_month = '0' + next_month
                if (pvs_year == year) and (pvs_month == month) and (subs_year == year) and (subs_month == month):
                    return year + '-' + month + '-' + pvs_day + '/' + year + '-' + month + '-' + subs_day
                elif (pvs_year == year) and (pvs_month == month):
                    return year + '-' + month + '-' + pvs_day + '/' + year + '-' + next_month + '-01'
                elif (subs_year == year) and (subs_month == month):
                    return year + '-' + month + '-01/' + year + '-' + month + '-' + subs_day
                else:
                    return year + '-' + month + '-01/' + year + '-' + next_month + '-01'