# AUTOGENERATED! DO NOT EDIT! File to edit: 54-utility-functions.ipynb (unless otherwise specified).

__all__ = ['new_file', 'normalize']

# Cell

def new_file(files_list):
    with open('new_file.xml', 'w', encoding = "utf-8") as outfile:
        for names in files_list:
            with open(names, encoding = "utf-8") as infile:
                outfile.write(infile.read())
            outfile.write("\n")

    return

# Cell

def normalize(text):
    '''
    normalizes transcribed text by expanding abbreviations, correcting idiosyncratic spellings, etc.
        text: text to be normalized, as a string

        returns: normalized text, as a string
    '''

    return text