# AUTOGENERATED! DO NOT EDIT! File to edit: 12-ssda-xml-parser.ipynb (unless otherwise specified).

__all__ = ['parse_xml']

# Cell
import pandas as pd

# Cell
def parse_xml(file_name):
    master_xml = open(file_name,"r",encoding='utf-8')
    vol_titls = []
    vol_ids = []
    entry_txts = []
    entry_ids = []
    fol_ids = []
    curr_vol_titl = ""
    curr_vol_id= ""
    curr_fol_id = ""
    curr_entry = ""

    in_entry = False

    for line in master_xml:
        if (line.find('<') != -1) and (line.find('<', line.find('<') + 1) != -1):
            line_content = line[line.find('>') + 1:line.find('<', line.find('<') + 1)]
        elif line[len(line) - 2] == '-':
            line_content = line[:len(line) - 2]
        else:
            line_content = line[:len(line) - 1] + ' '

        if "<volumeTitle>" in line:
            curr_vol_titl = line_content
            #set current volume title
        elif "<volumeIdentifier>" in line:
            curr_vol_id = line_content
        #set current volume identifier
        elif "<itemIdentifier>" in line:
            entry_id = 0
            curr_fol_id = line_content
        #set current folio id
        elif "<entry>" in line:
            entry_id += 1
            in_entry = True
            curr_entry = ""
        #toggle in entry flag
        elif in_entry and (not "</entry>" in line):
            curr_entry += line_content
        #add line to current entry
        elif in_entry and ("</entry>" in line):
            in_entry = False
        #toggle entry flag, append all current variables to lists
            vol_titls.append(curr_vol_titl)
            vol_ids.append(curr_vol_id)
            fol_ids.append(curr_fol_id)
            entry_txts.append(curr_entry)
            entry_ids.append(curr_fol_id + '-' + str(entry_id))

    columns = {'vol_titl':vol_titls, 'vol_id':vol_ids, 'fol_id':fol_ids, 'text':entry_txts, 'entry_no':entry_ids}

    df = pd.DataFrame(columns)
    return df
